### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by panesofglass** [Tachyus/gluon#15]
I think the only jQuery dependency we have is for `JQueryPromise` and use of `$.ajax`. Could we consider returning an interface that matches basic patterns of `JQueryPromise` using only `XmlHttpRequest2`? Same for use of `$.ajax` which is entirely internal.

[typescript-deferred](https://www.npmjs.com/package/typescript-deferred) might be worthwhile to investigate.

**Comment by t0yv0** [comment]
Are you interested in removing runtime or type-level jQuery dependency? I think currently it is only at type/link level. That is, there are enough overloads in Gluon.Client to be able to ship apps without jQuery at runtime. 

For the type-level dependency, I would like to be lazy and wait until some "standard" promise interface emerges (maybe from the ES6-7 discussions). You are probably more up-to-date with the space than I am. So if typescript-deferred is it, I'd be OK with that.

**Comment by panesofglass** [comment]
Working on this in #31

**Comment by panesofglass** [comment]
I think the right replacement is to use the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API).
