### ISSUE TITLE
remove NuGet dependency of jQuery.TypeScript.DefinitelyTyped

### ISSUE THREAD

**Issue by ctaggart** [Tachyus/gluon#17]
https://www.nuget.org/packages/Gluon.Client/1.0.2
![image](https://cloud.githubusercontent.com/assets/80104/13364773/afe7d60c-dc85-11e5-9785-b7f772b6fca2.png)

That dependency should be removed. TypeScript users may choose to manage their TypeScript dependencies outside of NuGet, such as using [typings](https://www.npmjs.com/package/typings).

**Comment by panesofglass** [comment]
Is it possible to also remove the `/// <reference path="typings/jquery/jquery.d.ts" />` at the top of `Gluon.ts`? I tried before but could not get it to work. Paket currently places this file in the root of the `Scripts\typings` folder.

**Comment by t0yv0** [comment]
I am working on it.

**Comment by ctaggart** [comment]
For the nuget dependency, just remove this line:
https://github.com/Tachyus/gluon/blob/master/src/Gluon.Client/paket.template#L18
