### ISSUE TITLE
Remove Gluon.js.map from NuGet package

### ISSUE THREAD

**Issue by panesofglass** [Tachyus/gluon#20]
`Gluon.js.map` provides a source map to `Gluon.ts`, which we don't ship, so it's not useful to consumers. I don't see `Gluon.min.js` in the package, so we should probably just stick to shipping just `Gluon.d.ts` and `Gluon.js`. The changes to MSBuild are less clear to me, so maybe @t0yv0 or @ctaggart can tackle the necessary packaging changes.

**Comment by t0yv0** [comment]
I noticed that yes. What if we ship it? Will it break some consumer build stories? A source map to TypeScript-generated JavaScript is not likely to be very useful either. 

Maybe we can ship it but not in Content folder, so people can automate a little more carefully what they want to do with this.

**Comment by t0yv0** [comment]
So currently `Gluon.Client` package is shipping these files:

    Content/Scripts/Gluon.js
    Content/Scripts/Gluon.js.map # maps to typescript
    Content/Scripts/Gluon.min.js
    Content/Scripts/typings/Gluon.d.ts

What if we ship Content/Scripts/Gluon.ts ? Will this help with sourcemaps without breaking compilation strategies? Or simply remove Gluon.js.map for now?

I am a little wary of shipping things in Content/* because NuGet and Paket have special treatment for these files that can get in the way. For example, they can put TS files in your source and accidentally screw up compilation pipeline. Maybe we could ship these files in a different folder so that client build automation can explicitly decide to use them.

CC @ctaggart

**Comment by panesofglass** [comment]
Another option is to just not use a NuGet package and store the generated files in a `dist` folder, then use Paket to pull the files we want. We could then place any and all generated files there.

**Comment by panesofglass** [comment]
@t0yv0, btw, is there a `Gluon.min.js.map`? That would be quite helpful to include, as well.

**Comment by t0yv0** [comment]
dist - that's a no, I don't want to enforce users to use Paket. Eventually I'd like a simple-minded C#-NuGet-VS worklfow for this project to help with popularity for people who do not know or care about Paket :)

I lost Gluon.min.js.map but I can try to restore that. Unfortunately the only thing I know it will be pointing to .js file, not .ts file. I am not sure how to compose maps to point to origin. I might need to learn more. Anyway I think the point is I want my sourcemaps to point to TypeScript source not JS compilation output.

**Comment by panesofglass** [comment]
@t0yv0, I think we should prefer a `Gluon.min.js.map` pointing only at the `Gluon.js` file since most will just want to consume the `Gluon.d.ts` and `Gluon.js` files.

With respect to the `Content` folder, I think it's best to remain consistent with NuGet practices if you want to eventually get this working for a broad reach, i.e. C#. However, I think NuGet 3 is also moving away from `Content`. ASP.NET 6 (for .NET Core) is dependent on `npm` for front-end package management, from what I can tell.
