### ISSUE TITLE
Add support for string literal types

### ISSUE THREAD

**Issue by chrisgervang** [Tachyus/gluon#26]
Sometimes I have a scenario where I'd like type safety for string literals in typescript. Typescript recently introduced this feature. Ex:

```
TypeScript
type ValidStrings = "blue" | "red" | "green orange"
```

One idea is to add an annotation in F# above a discriminated union so the gluon compiler knows the union should generate as a string literal type in typescript instead of a union type. Ex:

```
F#
[<StringLiteral>]
type ValidStrings =
    | ``blue``
    | ``red``
    | ``green orange``
```

**Comment by panesofglass** [comment]
We are pretty close to this now, though not quite.

``` fsharp
type ValidStrings =
    | blue
    | red
    | green
```

``` typescript
interface blue { tag: "blue" }
interface red { tag: "red" }
interface green { tag: "green" }
type ValidStrings = blue | red | green
```

I think adding string literals should be fairly easy at this point (approx 1 day).

**Comment by panesofglass** [comment]
I tried the latter approach of generating a string literal type from the tags, but you cannot use the generated string literal type like so:

``` typescript
// Generated.ts
export interface Blue { tag: "Blue";}
export interface Red { tag: "Red";}
export interface GreenOrange { tag: "GreenOrange";}
export type Color = Blue | Red | GreenOrange;
export type ColorTags = "Blue" | "Red" | "GreenOrange";

// App.ts
function chooseColor(color: ColorTags): Color {
    return { tag: color }; // Types of property 'tag' are incompatible.
}
```

**Comment by panesofglass** [comment]
I figured this out and deployed it in version 2.0.2.
