### ISSUE TITLE
Clone and build does not work

### ISSUE THREAD

**Issue by liammclennan** [Tachyus/gluon#4]
How can I build gluon?

I tried building in Visual Studio 2015 without success. I tried running build.fsx without success.

**Comment by panesofglass** [comment]
I just did a clean clone on Windows with VS 2015 (and 2013) and a Mac with mono 4.2.1 running `build.ps1` and `build.sh`, respectively. Everything worked just fine. Would you mind posting the output showing failure?

**Comment by panesofglass** [comment]
It may or may not be worth noting that I previously only had VS 2015 on my Windows Server 2012 R2 VM, and gluon built fine in that setup. I installed 2013 to try to build visualfsharp.

**Comment by liammclennan** [comment]
Thanks. I had not tried build.ps1.
